version: '3.9'
services:
  app:
    build:
      context: .  # Utilise le Dockerfile dans le répertoire courant
      dockerfile: Dockerfile
    container_name: pokemon-app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pokemon-app.rule=Host(`pokemon.dai`)"  # Remplacez par votre hostname réel
      - "traefik.http.services.pokemon-app.loadbalancer.server.port=7000"  # Port interne exposé par l'application
      - "traefik.http.routers.pokemon-app.entrypoints=websecure"  # Utiliser HTTPS
      - "traefik.http.routers.pokemon-app.tls.certresolver=myresolver"  # Résolveur de certificat
    volumes:
      - ./pokemon-api.jar:/opt/app/pokemon-api.jar

  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api=true"  # Activer l'API Traefik
      - "--api.dashboard=true"  # Activer le tableau de bord
      - "--providers.docker=true"  # Activer le fournisseur Docker
      - "--entrypoints.web.address=:80"  # Entrypoint HTTP
      - "--entrypoints.websecure.address=:443"  # Entrypoint HTTPS
      - "--entrypoints.dashboard.address=:6969"  # Entrypoint pour le tableau de bord
      - "--certificatesresolvers.myresolver.acme.httpChallenge=true"  # Challenge HTTP pour Let's Encrypt
      - "--certificatesresolvers.myresolver.acme.httpChallenge.entryPoint=web"
      - "--certificatesresolvers.myresolver.acme.email=danitiag.fariados@hes-so.ch"  # Email pour Let's Encrypt
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"  # Emplacement de stockage des certificats
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.localhost`)"  # Remplacez par votre hostname réel
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.entrypoints=dashboard"  # Utiliser le port 6969
      - "traefik.http.routers.traefik-dashboard.tls.certresolver=myresolver"  # Sécuriser avec TLS
    ports:
      - "80:80"  # HTTP
      - "443:443"  # HTTPS
      - "6969:6969"  # HTTPS
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"  # Fournisseur Docker
      - "./letsencrypt:/letsencrypt"  # Stockage persistant des certificats
