version: '3.9'
services:
  app:
    build:
      context: .  
      dockerfile: Dockerfile
    container_name: pokemon-app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pokemon-app.rule=Host(`dai.servecounterstrike.com`)" 
      - "traefik.http.services.pokemon-app.loadbalancer.server.port=7000" 
      - "traefik.http.routers.pokemon-app.entrypoints=websecure" 
      - "traefik.http.routers.pokemon-app.tls.certresolver=myresolver"  
    volumes:
      - ./pokemon-api.jar:/opt/app/pokemon-api.jar

  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api=true"  
      - "--api.dashboard=true"  
      - "--providers.docker=true" 
      - "--entrypoints.web.address=:80" 
      - "--entrypoints.websecure.address=:443" 
      - "--entrypoints.dashboard.address=:6969"
      - "--certificatesresolvers.myresolver.acme.httpChallenge=true" 
      - "--certificatesresolvers.myresolver.acme.httpChallenge.entryPoint=web"
      - "--certificatesresolvers.myresolver.acme.email=danitiag.fariados@hes-so.ch" 
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`dai.servecounterstrike.com`)"  
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.entrypoints=dashboard"
      - "traefik.http.routers.traefik-dashboard.tls.certresolver=myresolver" 
    ports:
      - "80:80"  
      - "443:443" 
      - "6969:6969"  
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"  
      - "./letsencrypt:/letsencrypt"
